options:
  debug:
    type: boolean
    default: False
    description: "Enable debug logging"
  verbose:
    type: boolean
    default: False
    description: "Enable verbose logging"
  hostname:
    type: string
    description: |
      Hostname reported by all cinder agents. It defaults to the computer hostname.
      If this is set, only the cinder volume agent from the leader unit will be
      running. This option should be set when shared storage is used in order
      to avoid cinder reporting wrong storage available.
  openstack-version:
    type: string
    default: pike
    description: |
      Version of Openstack Cinder to install. This is used to generate
      conf file and to choose the default installer url in case it is not
      specified in the config option. Choices are:
       * newton
       * ocata
       * pike
  enabled-backends:
    type: string
    default: "iscsi"
    description: |
      A space-separated list of enabled backends for Cinder Volume. Valid choices are:
       * iscsi
       * smb
  ad-computer-group:
    type: string
    default: "cinder-group"
    description: "Computer group that will be joined after adding AD relation"
  ad-user:
    default: "cinder-user"
    type: string
    description: "User that will created after adding AD relation"
  ad-ou:
    type: string
    description: "Organizational unit container used after joining AD domain"
  delay-service-start:
    type: boolean
    default: False
    description: |
      Delay starting the cinder-volume service until the relation with WSFC
      that creates a cluster service is established.
  log-dir:
    type: string
    description: |
     Log folder location. Defaults to: '<system_drive_letter>:\OpenStack\Log'.
  max-used-space-ratio:
    type: string
    description: |
      Percent of actual usage of the underlying volume before no new volumes
      can be allocated to the volume destination. Used by the smbfs driver.
      Defaults to '1.0'.
  oversubmit-ratio:
    type: string
    description: |
      This will compare the allocated to available space on the volume
      destination. If the ratio exceeds this number, the destination will
      no longer be valid. Used by the smbfs driver. Defaults to '1.0'.
  default-volume-format:
    type: string
    description: |
      Default format that will be used when creating volumes if no volume
      format is specified. Used by the smbfs driver. Defaults to 'vhdx'.
  image-volume-cache-enabled:
    type: boolean
    default: False
    description: "Enable caching for the volumes created from an image"
  image-volume-cache-max-size-gb:
    type: int
    default: 200
    description: "Maximum amount of GB used for image volume caching"
  image-volume-cache-max-count:
    type: int
    default: 10
    description: "Maximum number of volumes to be cached"
  installer-url:
    type: string
    description: |
      Overwrite default installer location. Take care to set the correct openstack-version
      as that will be used by the charm to pick the correct config templates.
      If you use this option, you may enable file integrity checking by specifying
      an md5sum at the end of the URL as follows:
        https://example.com/installer.msi#md5=<hash>
  cluster-role-name:
    default: cinder-cluster
    type: string
    description: "Name for the cluster generic service role"
  rabbit-user:
    default: cinder
    type: string
    description: "Username used to access RabbitMQ queue"
  rabbit-vhost:
    default: openstack
    type: string
    description: "RabbitMQ virtual host"
  database:
    default: cinder
    type: string
    description: "Database to request access"
  database-user:
    default: cinder
    type: string
    description: "Username to request database access"
  change-hostname:
    default: False
    type: boolean
    description: |
      The hostname set inside the newly spawned machine is usually the same as
      the name of the instance being spawned. In cases where the instance name
      is larger then 15 characters (maximum size for windows NetBios names), the
      instance name gets truncated to the first 15 characters. This creates a problem,
      as hostnames in active directory, for example, are very important. Having more
      then one machine with the same hostname try to join the same domain, will
      create trust issues.
      This option allows changing the hostname of the current running system to a
      combination of the first 14 (or less, depending on how many digits the unit number has)
      characters of the charm name and the unit number. While this is not infallible,
      It does have less of a chance of creating hostname conflicts.
